version: '3.8'

services:
  db:
    image: postgres:16.8
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - CLIENT_URL=${CLIENT_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '8010:8010'
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always
    # ports:
    #   - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  db_data:
  redisdata:
    driver: local
