version: '3.8'

services:
  gyustay-db:
    image: postgres:16.8
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - gyubuntu_net

  gyustay-server:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - CLIENT_URL=${CLIENT_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '8010:8000'
    depends_on:
      - gyustay-db
      - gyustay-redis
    networks:
      - gyubuntu_net

  gyustay-redis:
    image: redis:latest
    restart: always
    # ports:
    #   - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - gyubuntu_net

volumes:
  db_data:
  redisdata:
    driver: local

networks:
  gyubuntu_net:
    external: true
